---
title: "Simple_example"
output:
  rmarkdown::html_vignette:
    toc : true
    toc_depth: 3
    number_sections: yes
vignette: >
  %\VignetteIndexEntry{Simple_example}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(BayCausal)
```

# Basic setup
```{r}
seed <- 0
P_star <- 1
Nit <- 10000
burn <- 5000
thin <- 10
```

# Generate toy data
```{r}
data <- generate_toy_data(include_B = FALSE, include_X = FALSE)
```


# Set up prior, initial values, and chain 
```{r}
mh_setup_lst <- set_mh_default()
prior_lst <- set_prior_default(data,1)
init_lst <- set_init_default_wo_x(seed, P_star, data, prior_lst)
chain_setup_lst <- set_chain(Nit, burn, thin, seed)
```

# Run the algorithm
```{r}
res <- lingfa_wo_x(data, mh_setup_lst, init_lst, prior_lst, chain_setup_lst, FALSE)
```

# Result

## P_star

### Truth
The true value of P_star is `r data$P`.

### MCMC
```{r}
table(extract_P_star(res))
```


## L

### Truth
```{r}
round(data$L,2)
```

### MCMC
```{r}
round(extract_post_mean(res, "L", get_mode(extract_P_star(res))),2)
```

### L post processed
```{r}
res_processed <- post_process_L(res,  order_flag = TRUE, pos_sign = TRUE, cutoff = 0.1)
round(extract_post_mean(res_processed, "L", get_mode(extract_P_star(res))),2)
```

### P_star post processed
```{r}
table(extract_P_star(res_processed))
```


