# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rinvgamma_rcpp <- function(a, b) {
    .Call(`_glvcausal_rinvgamma_rcpp`, a, b)
}

rmvn_rcpp <- function(n, mean, sigma) {
    .Call(`_glvcausal_rmvn_rcpp`, n, mean, sigma)
}

